### ISSUE TITLE
Plugin doesn't use HTTP Proxy

### ISSUE THREAD

**Issue by colinfrei** [jjw24/Wox.Plugin.Todoist#15]
It seems that the plugin doesn't use the Flow Launcher Proxy settings when making API calls, that causes it to not work in our corporate environment.

Would it be possible to make it use the proxy settings if there are any set? Unfortunately I couldn't find any documentation around that on the Flow Launcher site.

**Comment by deefrawley** [comment]
Hi. If you go into Flow's settings have you set the proxy in the HTTP Proxy settings tab?

**Comment by colinfrei** [comment]
I did have the proxy set, but that doesn't seem to have been the issue. In any case, I'm not able to reproduce it anymore, works as expected now.
Thanks, and sorry for the distraction.
