### ISSUE TITLE
Todoist API requires bump from V8 to V9 after October 2022

### ISSUE THREAD

**Issue by 0xCCY** [jjw24/Wox.Plugin.Todoist#5]
Is this repo still active? I can submit a pull request but I'm not sure how to build and test it out.

I just discover this yesterday and now it's not working anymore :(

**Comment by jjw24** [comment]
Hey, it's active.

You can test it by building the plugin to Flow's UserData/plugin directory and restart flow. Type `userdata` via flow and you will get to the containing directory.

**Comment by 0xCCY** [comment]
Thanks, Flow Launcher plugin development docs need to be update to reflect that.

PR #6 should fix this.

**Comment by jjw24** [comment]
Yeah very true, I keep forgetting to despite having several same question about how to test plugins. Would you mind doing it? I'm afk atm.

**Comment by 0xCCY** [comment]
> Yeah very true, I keep forgetting to despite having several same question about how to test plugins. Would you mind doing it? I'm afk atm.

Sure, will see what I can do.
