### ISSUE TITLE
Failed to create tasks

### ISSUE THREAD

**Issue by nihitkhandelwal-eng** [jjw24/Wox.Plugin.Todoist#7]
I have been getting an error since 06-Dec-22, I have shared a screenshot here for the same.
I changed the api key but uninstalling & reinstalling finally worked. 

I just wanted to report this.
![brave_01aP4r7n3k](https://user-images.githubusercontent.com/68077636/206181985-6a10f234-c360-486b-a9fe-eb1d01dff325.png)

**Comment by nguyenhai86** [comment]
Me too. I uninstalling & reinstalling and new API key but it's not work.

**Comment by jjw24** [comment]
This should be fixed with PR #10. Please update to version 2.0.3.

Please reopen if not the case.
