### ISSUE TITLE
Last failed request returned HTTP 403 Forbidden

### ISSUE THREAD

**Issue by astroboii47** [jjw24/Wox.Plugin.Todoist#8]
![Snipaste_2022-12-27_11-04-08](https://user-images.githubusercontent.com/58410541/209589410-36de8a61-2bee-4ed1-b1c9-63a47aa41358.png)

Seem to get this error no matter what - tried using a new API key and reinstalling the plugin :\

**Comment by astroboii47** [comment]
Seems to have something to do with needing to update Todoist API to v9 and Newtonsoft.Json to 13, based off DanielBV's master branch: https://github.com/DanielBV/Wox.Plugin.Todoist/tree/master/src

**Comment by jjw24** [comment]
Will take a look

**Comment by nihitkhandelwal-eng** [comment]
Same here

**Comment by Ketan-Agarwal** [comment]
any update? having the same issue

**Comment by jjw24** [comment]
Will be looking at fixing this next week, haven't had the time to look at it yet.

**Comment by lsilvam** [comment]
I am also having the same issue

**Comment by jjw24** [comment]
Fixed :) Please update to version 2.0.3

**Comment by lsilvam** [comment]
thank you :) it is working 👍 (of course)
